main/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from .import views

#Definir nombre de la aplicación
app_name = 'main'

#Importar urls de las páginas de la aplicación con sus vistas
urlpatterns = [
    path('', views.IndexView.as_view(), name = "home"),
    path('blog/', views.BlogView.as_view(), name="blogs"),
    path('blog/<slug:slug>', views.BlogDetailView.as_view(), name="blog"),
    path('blog-create', views.blogcreate, name="blog-create"),
    path('manga', views.MangaView.as_view(), name="mangas"),
    path('manga/<slug:slug>', views.MangaDetailView.as_view(), name="manga"),
    path('anime', views.AnimeView.as_view(), name="animes"),
    path('anime/<slug:slug>', views.AnimeDetailView.as_view(), name="anime"),
    path('login', views.loginRegister, name="login"),
]

shueishaWebApp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views

urlpatterns = [ #Incluir urls de...
    path('admin/', admin.site.urls), #páginas de panel admin
    path('', include('main.urls', namespace='main')), #app main
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')), #páginas de ckeditor
    path('logout/', views.LogoutView.as_view(), name='logout'), #página por defecto de logout
]

if settings.DEBUG: #Si DEBUG está activado, actuar como servidor de archivos estáticos
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.

#Modelos de las clases en la base de datos

class Autor(models.Model):

    class Meta:
        verbose_name_plural = 'Autores'
        verbose_name = 'Autor'
    
    nombre = models.CharField(max_length=100, null=True)
    avatar = models.ImageField(blank=True, null=True, upload_to="avatar")
    bio = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'{self.nombre}'

class Media(models.Model):

    class Meta:
        verbose_name_plural = 'Media Files'
        verbose_name = 'Media'
        ordering = ["name"] #ordenar archivos multimedia por nombre
	
    image = models.ImageField(blank=True, null=True, upload_to="media")
    url = models.URLField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    is_image = models.BooleanField(default=True)

    def save(self, *args, **kwargs): #Al guardar, revisar si es una imagen o la dirección a una
        if self.url:
            self.is_image = False
        super(Media, self).save(*args, **kwargs)
    def __str__(self):
        return self.name

class Etiqueta(models.Model):
    class Meta:
       verbose_name_plural = 'Etiquetas'
       verbose_name = 'Etiqueta'
       ordering = ['nombre'] #ordenar etiquetas por nombre
    
    nombre = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.nombre

class Blog(models.Model):

    class Meta:
        verbose_name_plural = 'Blogs'
        verbose_name = 'Blog'
        ordering = ["-fecha"] #ordenar blogs por fecha

    fecha = models.DateTimeField(auto_now_add=True)
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE, null=True)
    titulo = models.CharField(max_length=200, blank=True, null=True)
    descripcion = models.CharField(max_length=500, blank=True, null=True)
    contenido = RichTextUploadingField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    imagen = models.ImageField(blank=True, null=True, upload_to="blog")
    etiquetas = models.ManyToManyField(Etiqueta, blank=True)

    def save(self, *args, **kwargs): #Al guardar, crear el slug a partir del título del blog
        if not self.id:
            self.slug = slugify(self.titulo)
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.titulo

    def get_absolute_url(self): #Método para obtener el url del objeto blog con su slug
        return f"/blog/{self.slug}"

class Mangaka(models.Model):
    class Meta:
        verbose_name_plural = 'Mangakas'
        verbose_name = 'Mangaka'
        ordering = ['nombre'] #Ordenar mangakas por nombre
    
    nombre = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.nombre

class Manga(models.Model):
    class Meta:
        verbose_name_plural = 'Mangas'
        verbose_name = 'Manga'
        ordering = ['nombre'] #Ordenar mangas por nombre
    
    nombre = models.CharField(max_length=200, null=True)
    mangaka = models.ForeignKey(Mangaka, on_delete=models.CASCADE)
    publicacion = models.DateField()
    volumenes = models.IntegerField(default=1)
    descripcion = models.CharField(max_length=500, blank=True, null=True)
    imagen = models.ImageField(blank=True, null=True, upload_to="manga")
    etiquetas = models.ManyToManyField(Etiqueta, blank=True)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.nombre
    
    def save(self, *args, **kwargs): #Al guardar, crear un slug a partir del nombre del manga
        if not self.id:
            self.slug = slugify(self.nombre)
        super(Manga, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return f"/manga/{self.slug}" #Método para obtener el url del objeto manga con su slug

class Anime(models.Model):
    class Meta:
        verbose_name_plural = 'Animes'
        verbose_name = 'Anime'
        ordering = ['nombre']
    
    nombre = models.CharField(max_length=200, null=True)
    primera_emision = models.DateField()
    capitulos = models.IntegerField(default=1)
    duracion = models.DurationField(null=True)
    descripcion = models.CharField(max_length=500, blank=True, null=True)
    imagen = models.ImageField(blank=True, null=True, upload_to="anime")
    etiquetas = models.ManyToManyField(Etiqueta, blank=True)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.nombre

    def save(self, *args, **kwargs): #Al guardar, crear un slug a partir del nombre del anime
        if not self.id:
            self.slug = slugify(self.nombre)
        super(Anime, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return f"/anime/{self.slug}" #Método para obtener el url del objeto anime con su slug

class Review(models.Model):
    class Meta:
        verbose_name_plural = 'Reviews'
        verbose_name = 'Review'
        ordering = ['-fecha'] #ordenar reviews por fecha
        """ constraints = [
            models.CheckConstraint(
                name="%(app_label)s_%(class)s_anime_or_manga",
                check=(
                    models.Q(manga__isnull=True, anime__isnull=False)
                    | models.Q(manga__isnull=False, anime__isnull=True)
                ),
            )
        ] """
    
    opciones_calif = [(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')] #Restringir la valoración de 1 a 5
    
    usuario = models.CharField(max_length=100, null=True)
    manga = models.ForeignKey(Manga, on_delete=models.CASCADE, blank=True, null=True, default=None)
    anime = models.ForeignKey(Anime, on_delete=models.CASCADE, blank=True, null=True, default=None)
    fecha = models.DateTimeField(auto_now_add=True)
    estrellas = models.PositiveIntegerField(default=1, null=True, choices=opciones_calif)
    mensaje = models.CharField(max_length=500, null=True)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Blog, Review

#Formularios

class BlogCreateForm(forms.ModelForm): #Formulario para crear blogs
    class Meta:
        model = Blog
        fields = ['autor', 'titulo', 'descripcion', 'contenido', 'imagen', 'etiquetas']
        widgets = {
            'descripcion': forms.Textarea(attrs={'cols':200, 'rows': 4,'style': "width: 70%;"}) #Mostrar el campo de descripción como un campo de texto multilínea
        }

class CreateReview(forms.ModelForm): #Formulario para crear reviews
    class Meta:
        model = Review
        fields = ['manga', 'anime', 'usuario', 'estrellas', 'mensaje']

class CreateUserForm(UserCreationForm): #Formulario para crear usuarios
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

main/views.py
from email import message
from typing_extensions import Self
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from .models import (
    Anime,
    Blog,
    Manga,
    Review
)
from .forms import BlogCreateForm, CreateReview, CreateUserForm
from django.http import HttpResponseRedirect
from django.views import generic
# Create your views here.

# View de la página principal
class IndexView(generic.TemplateView):
    template_name = "main/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        blogs = Blog.objects.all()[:6] #Tomar últimos 6 blogs y últimas 6 reviews
        reviews = Review.objects.all()[:6]
        
        context["blogs"] = blogs
        context["reviews"] = reviews #Anexar últimas reviews y blogs al contexto

        return context

# Clase base para obtener blogs recientes
class RecentBlogs(generic.base.ContextMixin):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        recent_blogs = Blog.objects.all()[:4] # Tomar 4 últimos blogs
        context["recentBlogs"] = recent_blogs # Anexar al contexto

        return context

# Clase base para obtener y enviar reviews dependiendo si es anime o manga
class GetReviews(generic.edit.FormMixin):
    form_class = CreateReview
    formSent = None
    
    def get_success_url(self):
        return self.request.path # retornar a la misma página al procesar una solicitud sin errores

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        reviews = None
        if isinstance(self.object, Manga):
            reviews = Review.objects.filter(manga=self.object) #Si es manga, obtener las reviews para este
        else:
            reviews = Review.objects.filter(anime=self.object) #Si no, obtener las reviews para el anime
        
        context["form"] = CreateReview() #Anexar formulario para crear review, las reviews en sí
        context["reviews"] = reviews
        context["loop_n"] = range(5, 0, -1) # Y un iterador en reversa de 5 a 0 para la valoración en estrellas

        return context

    # al procesar una solicitud
    def post(self, request, *args, **kwargs):
        self.object = self.get_object() # obtener objeto de lasolicitud
        form = self.get_form() # obtener formulario enviado

        if form.is_valid(): #Si el formulario no contiene errores
            form1 = form.save(commit=False)
            if isinstance(self.object, Manga): #Determinar si la review es para un manga o un anime y anexar la llave foránea
                form1.manga = self.object
            else:
                form1.anime = self.object
            form1.save()
            return self.form_valid(form1) #Llamar al método de formulario exitoso
        else:
            return self.form_invalid(form)

    def form_valid(self, form): #Si todo fue bien con el formulario, llamar este método
        form.save()
        messages.success(self.request, "Reseña publicada exitosamente") #Enviar mensaje de solicitud correcta al usuario
        return super().form_valid(form)
    
    def form_invalid(self, form): #Si hubo un error con el formulario, llamar este método
        messages.error(self.request, "Error al publicar reseña") #Enviar mensaje de error al usuario
        return super().form_invalid(form)

#Subclase de RecentBlogs para mostrar la lista de blogs
class BlogView(generic.ListView, RecentBlogs):
    model = Blog
    template_name = "main/blog.html"
    paginate_by = 4 # Mostrar 4 por página

    def get_queryset(self):
        return super().get_queryset().all() #Tomar todos los blogs sin filtrar

#Clase para mostrar los detalles de un solo blog
class BlogDetailView(generic.DetailView, RecentBlogs):
    model = Blog
    template_name = "main/blog-detail.html"

#Clase para mostrar un listado de los mangas
class MangaView(generic.ListView):
    model = Manga
    template_name = "main/manga.html"
    paginate_by = 10 #Mostrar 10 por página

    def get_queryset(self):
        return super().get_queryset().all() # Tomar todos los mangas sin filtrar

#Clase para mostrar los detalles de un solo manga con sus reviews al heredar de GetReviews
class MangaDetailView(generic.DetailView, GetReviews):
    model = Manga
    template_name = "main/manga-detail.html"

#Clase para mostrar el listado de los animes
class AnimeView(generic.ListView):
    model = Anime
    template_name = "main/anime.html"
    paginate_by = 10 #Mostrar 10 por página

    def get_queryset(self):
        return super().get_queryset().all()

#Clase para mostrar los detalles de un solo anime con sus reviews al heredar de GetReviews
class AnimeDetailView(generic.DetailView, GetReviews):
    model = Anime
    template_name = "main/anime-detail.html"

#Vista de método para crear blogs (requiere inicio de sesión)
@login_required(login_url='/login')
def blogcreate(request):
    form = None
    if request.method == "POST": #Si estamos recibiendo una solicitud POST
        form = BlogCreateForm(request.POST, request.FILES) #Tomar solicitud POST con archivos
        if form.is_valid(): #Si la solicitud es correcta redireccionar a la misma página
            form.save()
            return HttpResponseRedirect('/')
    else:
        form = BlogCreateForm() #Si no, anexar formulario al contexto
    return render(request, 'main/blog-create.html',{'form':form})

#Vista de método para manejar el registro e inicio de sesión
def loginRegister(request):
    if request.user.is_authenticated: #Si ya se inició sesión, devolver a la página principal
        return redirect('main:home')
    else:
        form = None
        if request.method == "POST": #Si no, tomamos la solicitud POST
            if 'password' in request.POST: #Si hay un campo llamado password, estamos lidiando con un inicio de sesión
                username = request.POST.get("username")
                password = request.POST.get("password")
                
                user = authenticate(request, username=username, password=password) #Intentar iniciar sesión con credenciales dadas

                if user is not None: #Si no obtuvimos un valor nulo, el inicio de sesión fue exitoso
                    login(request, user)
                    siguiente = request.GET.get('next')
                    if siguiente is None: return redirect('main:home') #Si el usuario no buscaba ir a otra página, redireccionarlo a la página principal
                    else: return redirect(siguiente)
                else:
                    messages.error(request, "Usuario o contraseña incorrecta")
            else:
                form = CreateUserForm(request.POST) #De otra manera, lidiamos con un registro
                if form.is_valid(): #Revisamos la validez del registro y si es válido creamos la cuenta
                    form.save()
                    user = form.cleaned_data.get('username')
                    messages.success(request, "Cuenta creada exitosamente, inicia sesión para acceder a la cuenta")

                    return redirect("main:login")
        context = {'form':form} #Anexar formulario al contexto
        return render(request, "main/login.html", context)

main/templates/main/anime-detail.html
{% extends 'main/title-detail.html' %}
{% load static %}
{% load duration_format %}

{% block title_fields %}
<li><label>Capítulos :</label>&nbsp;&nbsp;{{object.capitulos}}</li>
<li><label>Primera emisión :</label>&nbsp;&nbsp;{{object.primera_emision}}</li>
<li><label>Duración :</label>&nbsp;&nbsp;{{object.duracion|duration}} aprox. por capítulo</li>
{% endblock %}

main/templates/main/anime.html
{% extends 'main/title-base.html' %}
{% load static %}

{% block title_name %}Anime{% endblock %}

{% block title_url1 %}"{% url 'main:anime' slug=obj.slug %}"{% endblock %}

{% block title_date %}Primera emisión: {{obj.primera_emision}}{% endblock %}

{% block title_data %}{{obj.capitulos}} {% if obj.capitulos == 1 %} capítulo {% else %} capítulos {% endif %}{% endblock %}

{% block title_url2 %}"{% url 'main:manga' slug=obj.slug %}"{% endblock %}

{% block title_img %}
  {% if obj.imagen %}"{{obj.imagen.url}}"{% else %}""{% endif %}
  {% endblock %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Shueisha</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- styles -->
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">
  <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
  <link href="{% static 'js/google-code-prettify/prettify.css' %}" rel="stylesheet">
  <link href="{% static 'css/flexslider.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'color/orange.css' %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,600,400italic|Open+Sans:400,600,700" rel="stylesheet">
  {% block additionalCss %}
  {% endblock %}
  <!-- fav and touch icons -->
  <link rel="shortcut icon" href="{% static 'ico/favicon.ico' %}">
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'ico/apple-touch-icon-144-precomposed.png' %}">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'ico/apple-touch-icon-114-precomposed.png' %}">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'ico/apple-touch-icon-72-precomposed.png' %}">
  <link rel="apple-touch-icon-precomposed" href="{% static 'ico/apple-touch-icon-57-precomposed.png' %}">

  <!-- =======================================================
    Theme Name: Lumia
    Theme URL: https://bootstrapmade.com/lumia-bootstrap-business-template/
    Author: BootstrapMade.com
    Author URL: https://bootstrapmade.com
  ======================================================= -->
</head>


<body>
  <div id="wrapper">
    <header>
      <!-- Navbar
    ================================================== -->
      <div class="navbar navbar-static-top">
        <div class="navbar-inner">
          <div class="container">
            <!-- logo -->
            <div class="logo">
              <a href="{% url 'main:home' %}"><img src="{% static 'img/logo.svg' %}" alt="" /></a>
            </div>
            <!-- end logo -->

            <!-- top menu -->
            <div class="navigation">
              <nav>
                <ul class="nav topnav">
                  <li class="active">
                    <a href="{% url 'main:home' %}"><i class="icon-home"></i> Inicio </a>
                  </li>
                  <li>
                    <a href="{% url 'main:mangas' %}"><i class="icon-columns"></i>  Manga </a>
                  </li>
                  <li>
                    <a href="{% url 'main:animes' %}"> <i class="icon-film"></i> Anime </a>
                  </li>
                  <li>
                    <a href="{% url 'main:blogs' %}"><i class="icon-book"></i> Blog </a>
                  </li>
                  {% if user.is_authenticated %}
                  <li class="dropdown">
                    <a href="#"><i class="icon-user"></i> {{ user.get_username }} </a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'logout' %}?next={{request.path}}"><i class="icon-signout"></i> Salir</a></li>
                    </ul>
                  {% else %}
                  <li>
                    <a href="{% url 'main:login' %}"><i class="icon-user"></i> Ingresar </a>
                  {% endif %}
                  </li>
                </ul>
              </nav>
            </div>
            <!-- end menu -->

          </div>
        </div>
      </div>
    </header>
 
    {% block content %}
    {% endblock %}

    <!-- Footer
 ================================================== -->
    <footer class="footer">
      <div class="container">
        <div class="row">
          <div class="span4">
            <div class="widget">
              <h5>Interesting pages</h5>
              <ul class="regular">
                <li><a href="#">About our company</a></li>
                <li><a href="#">How we do all stuff</a></li>
                <li><a href="#">Our recent works</a></li>
                <li><a href="#">Press releases</a></li>
                <li><a href="#">Get in touch with us</a></li>
              </ul>
            </div>
          </div>
          <div class="span4">
            <div class="widget">
              <h5>Contacto</h5>
              <address>
								<i class="icon-home"></i> <strong>Lumia company, Inc.</strong><br>
								X104 Awesome ville, Suite AB12<br>
								Jakarta 12420 Indonesia
								</address>
              <p>
                <i class="icon-phone"></i> (123) 456-7890 - (123) 555-8890<br>
                <i class="icon-envelope-alt"></i> email@domainname.com
              </p>
            </div>
            <div class="widget">
              <ul class="social">
                <li><a href="#" data-placement="bottom" title="Twitter"><i class="icon-twitter icon-square icon-32"></i></a></li>
                <li><a href="#" data-placement="bottom" title="Facebook"><i class="icon-facebook icon-square icon-32"></i></a></li>
                <li><a href="#" data-placement="bottom" title="Linkedin"><i class="icon-linkedin icon-square icon-32"></i></a></li>
                <li><a href="#" data-placement="bottom" title="Pinterest"><i class="icon-pinterest icon-square icon-32"></i></a></li>
                <li><a href="#" data-placement="bottom" title="Google plus"><i class="icon-google-plus icon-square icon-32"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="verybottom">
        <div class="container">
          <div class="row">
            <div class="span6">
              <p>
                &copy; Shueisha Inc. - All right reserved
              </p>
            </div>
            <div class="span6">
              <div class="pull-right">
                <div class="credits">
                  <!--
                    All the links in the footer should remain intact.
                    You can delete the links only if you purchased the pro version.
                    Licensing information: https://bootstrapmade.com/license/
                    Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Lumia
                  -->
                  Created by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>

  </div>
  <!-- end wrapper -->
  <a href="#" class="scrollup"><i class="icon-chevron-up icon-square icon-48 active"></i></a>

  <script src="{% static 'js/jquery.js' %}"></script>
  <script src="{% static 'js/raphael-min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <script src="{% static 'js/google-code-prettify/prettify.js' %}"></script>
  <script src="{% static 'js/jquery.elastislide.js' %}"></script>
  <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
  <script src="{% static 'js/jquery.flexslider.js' %}"></script>
  <script src="{% static 'js/jquery-hover-effect.js' %}"></script>
  <script src="{% static 'js/animate.js' %}"></script>

  <!-- Template Custom JavaScript File -->
  <script src="{% static 'js/custom.js' %}"></script>
  {% block additionalJs %}
  {% endblock %}

</body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
    <section id="intro">

      <div class="container">
        <div class="row">
          <div class="span12">
            <!-- Place somewhere in the <body> of your page -->
            <div id="mainslider" class="flexslider">
              <ul class="slides">
                <li data-thumb="{% static 'img/onepiece.png' %}">
                  <img src="{% static 'img/onepiece.png' %}" alt="" />
                  <div class="flex-caption primary">
                    <h2>One Piece</h2>
                    <p style="font-weight: 600; font-size: 1.2em;">El libro más largo del mundo, con 21 450 páginas!!!</p>
                  </div>
                </li>
                <li data-thumb="{% static 'img/dbz.png' %}">
                  <img src="{% static 'img/dbz.png' %}" alt="" />
                  <div class="flex-caption warning">
                    <h2>Black Freezer</h2>
                    <p style="font-weight: 600; font-size: 1.2em;">Más fuerte que nunca</p>
                  </div>
                </li>
                <li data-thumb="{% static 'img/boruto.png' %}">
                  <img src="{% static 'img/boruto.png' %}" alt="" />
                  <div class="flex-caption success">
                    <h2>Boruto - capítulo 266</h2>
                    <p style="font-weight: 600; font-size: 1.2em;">Giro inesperado?...</p>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

    </section>
    <section id="maincontent">
      <div class="container">
        <div class="row">
          <div class="span12">
            <h4 class="rheading">Entradas recientes<span></span></h4>
            <div class="row">
              <div class="span3">

                <p class="hidden-phone">
                  Mantente al tanto de todas las noticias sobre tus mangas y animes favoritos en nuestro blog
                </p>

                <a href="{% url 'main:blogs'%}" class="btn btn-theme">Leer más</a>
              </div>

              <div class="span9">
                <div id="latest-work" class="carousel btleft">
                  <div class="carousel-wrapper">
                    <ul class="da-thumbs">
                      {% for b in blogs %}
                      <li onclick="location.href='{% url 'main:blog' slug=b.slug %}';">
                        <a href="{% url 'main:blog' slug=b.slug %}">
                          <div class="box">
                            {%if b.imagen %}
                            <div class="imagewrap">
                              <img src="{{b.imagen.url}}" alt="" />
                            </div>
                            {% endif %}
                            <div class="divcenter">
                              <h5>{{b.titulo}}</h5>
                            </div>
                            <div class="box-bottom"></div>
                          </div>
                        </a>
                      </li>
                      {% endfor %}
                    </ul>
                  </div>
                </div>

              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="span12">
            <h4 class="rheading">Últimas reseñas<span></span></h4>
            <div class="row">
              {% for r in reviews %}
              <div class="box span3" style="padding: 20px; width: 26%; margin-bottom: 20px;">
                <div class="testimonial">
                  <blockquote>
                    <p style="font-size: 1.15em;"><i class="icon-quote-left"></i>{{r.mensaje}}</p>
                  </blockquote>
                  <img src="{% static 'img/dummies/author-40.png' %}" class="img-circle left" alt="" />
                  <span class="author">{{r.usuario}}</span><br />en
                  {% if r.manga %}
                  <a href="{% url 'main:manga' slug=r.manga.slug %}">{{r.manga}}</a>
                  {% else %}
                  <a href="{% url 'main:anime' slug=r.anime.slug %}">{{r.anime}}</a>
                  {% endif %}
                </div>
              </div>
              {% endfor %}
            </div>
        </div>
      </div>
    </section>
{% endblock %}

main/templates/main/manga-detail.html
{% extends 'main/title-detail.html' %}
{% load static %}

{% block title_fields %}
<li><label>Mangaka :</label>&nbsp;&nbsp;{{object.mangaka}}</li>
<li><label>Publicación :</label>&nbsp;&nbsp;{{object.publicacion}}</li>
<li><label>Volúmenes :</label>&nbsp;&nbsp;{{object.volumenes}}</li>
{% endblock %}

main/templates/main/manga.html
{% extends 'main/title-base.html' %}
{% load static %}

{% block title_name %}Manga{% endblock %}

{% block title_url1 %}"{% url 'main:manga' slug=obj.slug %}"{% endblock %}

{% block title_date %}Publicación: {{obj.publicacion}}{% endblock %}

{% block title_data %}{{obj.volumenes}} {% if obj.volumenes == 1 %} volúmen {% else %} volúmenes {% endif %}{% endblock %}

{% block title_url2 %}"{% url 'main:manga' slug=obj.slug %}"{% endblock %}

{% block title_img %}
  {% if obj.imagen %}"{{obj.imagen.url}}"{% else %}""{% endif %}
  {% endblock %}